#!/bin/sh
#------------------------------------------------------------------------------
#
# Make/gemsConfig.sh
#
# PURPOSE
#
# Decides whether rhoFixedFlowFoam is built with the optional GEMS3K bridge
# (thermochemistry/gemsbridge, a plain-C ABI in libgemsbridge.so).
#
# The bridge is compiled in only when the environment variable
# LESTO_GEMSBRIDGE names a directory that holds both gemsbridge.h and
# libgemsbridge.so.  There is no default path: an unset, empty or incomplete
# LESTO_GEMSBRIDGE builds the solver without GEMS3K.
#
# Usage
#
#   sh Make/gemsConfig.sh <objectsDir>   called by Make/options on every wmake
#   sh Make/gemsConfig.sh -state         called by Allwmake
#
# With <objectsDir> the script writes <objectsDir>/gemsConfig.H, which
# defines LESTO_HAVE_GEMS (bridge compiled in) or not, and prints the bridge
# directory (nothing without the bridge) for Make/options.  The header is
# rewritten ONLY when its content changes.  Every source file that depends on
# the bridge includes it, so wmake's dependency tracking recompiles exactly
# those files after a toggle of LESTO_GEMSBRIDGE, even with a plain wmake,
# and the executable is then relinked with or without -lgemsbridge.
#
# In a bridge build the header also records the checksum of gemsbridge.h.
# wmkdepend cannot track gemsbridge.h itself (gemsEquilibrium.C includes it
# with angle brackets, see there), so an edit of the bridge header changes
# gemsConfig.H instead, and the same dependency recompiles the files that
# use the bridge.
#
# With -state the script only prints the current state, which Allwmake
# compares with and records in its stamp: the bridge directory, or "none".
#
# LESTO_GEMSBRIDGE must be an absolute path (see below); Allwmake makes a
# relative one absolute before it calls this script.
#
# Nothing may be written to stdout except the result: Make/options captures
# it with $(shell ...).
#
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# A relative LESTO_GEMSBRIDGE is refused: wmake runs in the solver directory,
# not in the directory the user typed the path in.  Allwmake resolves a
# relative path against the directory it is called from before it gets here.
# For Make/options the refusal is the marker LESTO_GEMSBRIDGE_RELATIVE on
# stdout, which it turns into a make error with the same explanation.
#------------------------------------------------------------------------------
case "${LESTO_GEMSBRIDGE:-}" in
    ""|/*)
        ;;
    *)
        echo "LESTO_GEMSBRIDGE=$LESTO_GEMSBRIDGE is a relative path; give an" \
             "absolute path, or build with Allwmake, which resolves it" \
             "against the directory it is called from." >&2
        echo LESTO_GEMSBRIDGE_RELATIVE
        exit 1
        ;;
esac

bridge=""
if [ -n "${LESTO_GEMSBRIDGE:-}" ] \
  && [ -f "$LESTO_GEMSBRIDGE/gemsbridge.h" ] \
  && [ -f "$LESTO_GEMSBRIDGE/libgemsbridge.so" ]
then
    bridge=$(cd "$LESTO_GEMSBRIDGE" 2>/dev/null && pwd -P)
fi

if [ "${1:-}" = "-state" ]
then
    echo "${bridge:-none}"
    exit 0
fi

objectsDir=${1:?usage: gemsConfig.sh <objectsDir> | -state}
mkdir -p "$objectsDir" || exit 1

header="$objectsDir/gemsConfig.H"
tmpHeader="$header.tmp$$"

{
    echo "/* Generated by Make/gemsConfig.sh: do not edit.  Rewritten only"
    echo "   when the GEMS3K bridge state (LESTO_GEMSBRIDGE) or the bridge"
    echo "   header changes. */"
    echo "#ifndef gemsConfig_H"
    echo "#define gemsConfig_H"
    if [ -n "$bridge" ]
    then
        echo "#define LESTO_HAVE_GEMS 1"
        echo "#define LESTO_GEMSBRIDGE_DIR \"$bridge\""
        echo "/* gemsbridge.h cksum: $(cksum < "$bridge/gemsbridge.h") */"
    else
        echo "#define LESTO_GEMSBRIDGE_DIR \"\""
    fi
    echo "#endif"
} > "$tmpHeader"

if cmp -s "$tmpHeader" "$header"
then
    rm -f "$tmpHeader"
else
    mv -f "$tmpHeader" "$header"
fi

echo "$bridge"

#------------------------------------------------------------------------------
