#!/bin/sh
#------------------------------------------------------------------------------
#
# Make/xgemsConfig.sh
#
# PURPOSE
#
# Decides whether rhoFixedFlowFoam is built with the optional xGEMS start-up
# call of the main branch (71bf192: rhoFixedFlowFoam.C equilibrates an xGEMS
# demo system once at start-up and prints the status).
#
# The call is compiled in only when the environment variable LESTO_XGEMS
# names an xGEMS installation prefix that holds both
# include/xGEMS/ChemicalEngine.hpp and lib/libxGEMS.so, e.g.
#
#   export LESTO_XGEMS=$HOME/Development/GEMS-Related/install
#
# (the prefix that the main branch linked unconditionally).  There is no
# default path: an unset, empty or incomplete LESTO_XGEMS builds the solver
# without xGEMS, and then neither the xGEMS nor the Eigen headers are needed.
#
# Usage
#
#   sh Make/xgemsConfig.sh <objectsDir>   called by Make/options on every wmake
#   sh Make/xgemsConfig.sh -state         called by Allwmake
#
# With <objectsDir> the script writes <objectsDir>/xgemsConfig.H, which
# defines LESTO_HAVE_XGEMS (xGEMS compiled in) or not, and prints the prefix
# (nothing without xGEMS) for Make/options.  The header is rewritten ONLY when
# its content changes.  rhoFixedFlowFoam.C includes it, so wmake's dependency
# tracking recompiles it after a toggle of LESTO_XGEMS, even with a plain
# wmake, and the executable is then relinked with or without -lxGEMS.  In an
# xGEMS build the header also records the checksum of ChemicalEngine.hpp,
# which wmkdepend cannot track (it is included with angle brackets), so a
# changed xGEMS installation recompiles rhoFixedFlowFoam.C too.  This is the
# scheme of Make/gemsConfig.sh for the GEMS3K bridge.
#
# With -state the script only prints the current state, which Allwmake
# compares with and records in its stamp: the prefix, or "none".
#
# LESTO_XGEMS must be an absolute path; Allwmake makes a relative one
# absolute before it calls this script.
#
# Nothing may be written to stdout except the result: Make/options captures
# it with $(shell ...).
#
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# A relative LESTO_XGEMS is refused: wmake runs in the solver directory, not
# in the directory the user typed the path in.  For Make/options the refusal
# is the marker LESTO_XGEMS_RELATIVE on stdout, which it turns into a make
# error with the same explanation.
#------------------------------------------------------------------------------
case "${LESTO_XGEMS:-}" in
    ""|/*)
        ;;
    *)
        echo "LESTO_XGEMS=$LESTO_XGEMS is a relative path; give an absolute" \
             "path, or build with Allwmake, which resolves it against the" \
             "directory it is called from." >&2
        echo LESTO_XGEMS_RELATIVE
        exit 1
        ;;
esac

prefix=""
if [ -n "${LESTO_XGEMS:-}" ] \
  && [ -f "$LESTO_XGEMS/include/xGEMS/ChemicalEngine.hpp" ] \
  && [ -f "$LESTO_XGEMS/lib/libxGEMS.so" ]
then
    prefix=$(cd "$LESTO_XGEMS" 2>/dev/null && pwd -P)
fi

if [ "${1:-}" = "-state" ]
then
    echo "${prefix:-none}"
    exit 0
fi

objectsDir=${1:?usage: xgemsConfig.sh <objectsDir> | -state}
mkdir -p "$objectsDir" || exit 1

header="$objectsDir/xgemsConfig.H"
tmpHeader="$header.tmp$$"

{
    echo "/* Generated by Make/xgemsConfig.sh: do not edit.  Rewritten only"
    echo "   when the xGEMS state (LESTO_XGEMS) or the xGEMS header"
    echo "   ChemicalEngine.hpp changes. */"
    echo "#ifndef xgemsConfig_H"
    echo "#define xgemsConfig_H"
    if [ -n "$prefix" ]
    then
        echo "#define LESTO_HAVE_XGEMS 1"
        echo "#define LESTO_XGEMS_DIR \"$prefix\""
        echo "/* ChemicalEngine.hpp cksum:" \
             "$(cksum < "$prefix/include/xGEMS/ChemicalEngine.hpp") */"
    else
        echo "#define LESTO_XGEMS_DIR \"\""
    fi
    echo "#endif"
} > "$tmpHeader"

if cmp -s "$tmpHeader" "$header"
then
    rm -f "$tmpHeader"
else
    mv -f "$tmpHeader" "$header"
fi

echo "$prefix"

#------------------------------------------------------------------------------
